set -g mouse on
set-hook -g session-created 'new-window "run-parts /etc/update-motd.d; read -p \"Press Enter to close...\""'
set-hook -g client-attached 'new-window "run-parts /etc/update-motd.d; read -p \"Press Enter to close...\""'
set -g default-command "exec bash --login"
